### ISSUE TITLE
Consider generating icon sets

### ISSUE THREAD

**Issue by programmist** [nkoterba/material-design-iconsets#1]
Polymer [core-icons](https://github.com/polymer/core-icons) has a similar project, however they include a script to generate new icon sets based on [material-design-icons](https://github.com/google/material-design-icons).  This would save you from having to hand-generate them each time the icons update.

**Comment by nkoterba** [comment]
Based on your suggestion I have updated the project to re-build the iconsets.  It's not super elegant or the best code but I imagine eventually these iconsets (or similar code generation) will be available from the material-design project.

See: a435bdaa8805e2f6aa3931b2139fdafb0fe982b6

**Comment by ThomasBurleson** [comment]
@nkoterba, @programmist - soon the Material Icons will be available as font-faces (instead of raw svgs). This means that `<md-icon md-font-icon="" />` can be used and the `angular.module('myApp', []).config( ... )` will **not** be required. 

> Until that time, this repository is a nice addition. Thank you @nkoterba
