### ISSUE TITLE
Wrong issue referenced in readme?

### ISSUE THREAD

**Issue by shannon** [nkoterba/material-design-iconsets#2]
I noticed you may have referenced the wrong issue in the opening paragraph of your readme. I think you meant this issue https://github.com/angular/material/issues/1668.

Nice work by the way.

**Comment by nkoterba** [comment]
@shannonmpoole Ah you're right...Updated the readme.  

Thanks for the feedback and the kudos.  The conversion code is not the most elegant or performant (did it at 1 AM in the morning) and I was experimenting with gulp, xml, svg libs, etc but it does the job and I imagine this project will eventually be OBE as Angular Material Design evolves and includes default iconsets, icons, or font-faces.
